name: Security

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kvwc
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: kvwc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "kvwc/.python-version"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install bandit
          pip install safety

      - name: Run security scan with bandit
        run: |
          bandit -r . > bandit_report.txt

      # - name: Run safety check
      #   run: |
      #     safety auth
      #     safety scan

      - name: Run Semgrep
        run: |
          pip install -q semgrep
          semgrep --config=p/default --metrics=off --text . > semgrep-results.txt

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const banditReport = fs.readFileSync('kvwc/bandit_report.txt', 'utf8');
            const semgrepReport = fs.readFileSync('kvwc/semgrep-results.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              **Bandit Security Scan Report:**
              \`\`\`
              ${banditReport}
              \`\`\`
              **Semgrep Security Scan Report:**
              \`\`\`
              ${semgrepReport}
              \`\`\`
              `
            })
